### ISSUE TITLE
你好，这个data数据是满足需求就能展示吗？为什么我的数据放到defaultDatas会出错能帮我看看吗？还是方法内部 有问题。

### ISSUE THREAD

**Issue by duoduoObama** [zhixiaotong/d3-graph-with-thumbnail#1]
{
    "nodes": [
        {
            "id": 52,
            "label": "测试1"
        },
        {
            "id": 79,
            "label": "测试w"
        },
        {
            "id": 14,
            "label": "测试wer"
        },
        {
            "id": 23,
            "label": "测试4"
        },
        {
            "id": 52,
            "label": "测试1"
        },
        {
            "id": 81,
            "label": "测试sd"
        },
        {
            "id": 17,
            "label": "测试sdf"
        },
        {
            "id": 23,
            "label": "测试4"
        }
    ],
    "edges": [
        {
            "source": 52,
            "target": 79
        },
        {
            "source": 79,
            "target": 14
        },
        {
            "source": 14,
            "target": 23
        }
    ]
}

**Comment by zhixiaotong** [comment]
@duoduoObama 很抱歉，很久没有上来github，忽略了很多信息。不过时隔这么久，相信你早已解决问题，这种错误一般都跟数据结构相关，仔细检查一下应该能发现问题所在。而且这个版本主要是为图谱的缩略图提供实现一种思路，也是比较早期的代码了，后续的更新也没有放上来。^_^

**Comment by zhixiaotong** [comment]
@duoduoObama 很抱歉，很久没有上来github，忽略了很多信息。不过时隔这么久，相信你早已解决问题，这种错误一般都跟数据结构相关，仔细检查一下应该能发现问题所在。而且这个版本主要是为图谱的缩略图提供实现一种思路，也是比较早期的代码了，后续的更新也没有放上来。^_^
