### ISSUE TITLE
有没有点击可以展开的功能啊

### ISSUE THREAD

**Issue by ddshiyu** [zhixiaotong/d3-graph-with-thumbnail#2]
希望能有个这个

**Comment by zhixiaotong** [comment]
sorry，此案例仅提供缩略图的思路，没考虑过将展开纳进来。其实，所谓的展开功能，其实就是：1、请求接口返回新数据；2、将原本隐藏的数据重新显示，可以添加节点然后重绘实现，这个不难，相信你可以做到。
